from __future__ import annotations

from ...llm.base import ToolSchema
from ...tools.schema import JSON_TO_PY

_HEADER = (
    "# AUTO-GENERATED by simple_agentic_system.sandbox.bridge.codegen — do not edit by hand.\n"
    "import runtime as _runtime\n"
)


def render_tool_module(specs: list[ToolSchema]) -> str:
    """Renders a python module source exposing every tool spec as a typed function
    (`tools.<name>(...)`) that dispatches to `runtime.call_tool` — the real MCP call to
    the ToolRegistry running on the host. Both this file and bridge/runtime.py get
    written into the sandbox container as sibling modules (`tools.py`, `runtime.py`),
    so plain `import tools; tools.calculator(a=1, b=2)` works with no MCP knowledge."""
    return _HEADER + "\n\n".join(_render_function(spec) for spec in specs) + ("\n" if specs else "")


def _render_function(spec: ToolSchema) -> str:
    properties: dict = spec.parameters.get("properties", {})
    required = set(spec.parameters.get("required", []))
    ordered = sorted(properties, key=lambda n: n not in required)  # required first, stable within group

    params_src = []
    for prop_name in ordered:
        py_type_name = JSON_TO_PY.get(properties[prop_name].get("type", "string"), str).__name__
        if prop_name in required:
            params_src.append(f"{prop_name}: {py_type_name}")
        else:
            params_src.append(f"{prop_name}: {py_type_name} | None = None")

    signature = ", ".join(params_src)
    call_args = ", ".join(f"{name}={name}" for name in ordered)
    doc = (spec.description or "").replace('"""', "'''")
    return f'def {spec.name}({signature}):\n    """{doc}"""\n    return _runtime.call_tool({spec.name!r}, {call_args})\n'
