from __future__ import annotations

import asyncio
import inspect
import io
import tarfile
from typing import Any

from ..tools.base import ToolResult
from ..tools.registry import ToolRegistry
from .bridge import runtime as _runtime_module
from .bridge.codegen import render_tool_module
from .session_registry import SessionContainerRegistry

PARAMETERS: dict[str, Any] = {
    "type": "object",
    "properties": {"code": {"type": "string"}},
    "required": ["code"],
}

_SANDBOX_DIR = "/sandbox"


class PythonExecTool:
    """Tool ("run_python") that executes LLM-authored python inside a session-affine
    sandbox container. No agent lives in the container — just the code. Tools are
    exposed to that code as plain python functions (`import tools; tools.foo(...)`),
    generated by bridge/codegen.py and backed by an MCP server over the same
    ToolRegistry (tools/server.py) reachable at `tools_mcp_url`.

    This Tool has no retry/self-repair logic of its own — wrap it with
    tools.RetryingTool + an AgentAsTool fixer for that (see tools/retrying.py).
    """

    name = "run_python"
    description = "Execute a python snippet in an isolated sandbox. Tools are available as `import tools`."
    parameters = PARAMETERS

    def __init__(
        self,
        session_id: str,
        session_registry: SessionContainerRegistry,
        tool_registry: ToolRegistry,
        *,
        tools_mcp_url: str,
    ):
        self._session_id = session_id
        self._session_registry = session_registry
        self._tool_registry = tool_registry
        self._tools_mcp_url = tools_mcp_url

    async def run(self, **kwargs: Any) -> ToolResult:
        code = kwargs["code"]
        container = await self._session_registry.get_or_create(self._session_id)

        tools_source = render_tool_module(self._tool_registry.list_specs())
        runtime_source = inspect.getsource(_runtime_module)
        await _write_files(container, {"tools.py": tools_source, "runtime.py": runtime_source, "main.py": code})

        exit_code, output = await _exec(
            container, ["python3", "main.py"], env={"TOOLS_MCP_URL": self._tools_mcp_url}
        )
        return ToolResult(output=output, is_error=exit_code != 0, error=output if exit_code != 0 else None)


async def _write_files(container: Any, files: dict[str, str]) -> None:
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w") as tar:
        for filename, content in files.items():
            data = content.encode("utf-8")
            info = tarfile.TarInfo(name=filename)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    buffer.seek(0)
    await asyncio.to_thread(container.put_archive, _SANDBOX_DIR, buffer)


async def _exec(container: Any, command: list[str], env: dict[str, str]) -> tuple[int, str]:
    result = await asyncio.to_thread(container.exec_run, command, environment=env, workdir=_SANDBOX_DIR)
    return result.exit_code, (result.output or b"").decode("utf-8", errors="replace")
